name: "dbt_mgul"
version: "1.0"
config-version: 2
profile: "user"

model-paths: ["models"]
macro-paths: ["macros"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_mgul:
    +materialized: view
    dbt_mgul:          # --> "models/dbt_mgul/"
      stage:           # --> "models/dbt_mgul/stage/"
        +materialized: view
        warehouse:
        +materialized: table

     

        
 
